# general settings
set -g default-terminal "screen-256color"
set-option -g mouse on

# make mouse scroll work
bind -n WheelUpPane copy-mode

# make new panes inherit current pane cwd
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
